# Config file for automatic testing at travis-ci.org

language: python

python:
  # - "3.4"
  # - "3.3"
  - "2.7"
  # - "2.6"
  # - "pypy"

env:
  - Z3_BRANCH=opt
  - Z3_BRANCH=master

# ### Not valid in cointainer-based builds. Commented out:
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y glpk-utils

addons:
  apt:
    packages:
      - glpk-utils

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - ./scripts/install_z3.sh
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - pulptest
  - which z3 && z3 --help
  - python setup.py test
