# Config file for automatic testing at travis-ci.org

language: python

python:
  # - "3.4"
  # - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# ### Not valid in cointainer-based builds. Commented out:
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y glpk-utils

addons:
  apt:
    packages:
      - glpk-utils

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - pulptest
  - python setup.py test
